/****************************************************************************
 * libgui
 * Daryl Borth 2009-2026
 * GuiInput.h
 *
 * Platform-agnostic input structures
 ***************************************************************************/
#pragma once

#include <cstdint>

/**
 * Universal platform-agnostic button bitmasks
 * Covers Wii, GameCube, and Wii U inputs
 */
enum GuiInputButtons : uint32_t {
	GUI_BTN_NONE    = 0,
	GUI_BTN_A       = (1 << 0),
	GUI_BTN_B       = (1 << 1),
	GUI_BTN_X       = (1 << 2),
	GUI_BTN_Y       = (1 << 3),
	GUI_BTN_1       = (1 << 4),
	GUI_BTN_2       = (1 << 5),
	GUI_BTN_UP      = (1 << 6),
	GUI_BTN_DOWN    = (1 << 7),
	GUI_BTN_LEFT    = (1 << 8),
	GUI_BTN_RIGHT   = (1 << 9),
	GUI_BTN_PLUS    = (1 << 10),  // Plus (Wii/Wii U) / Start (GC)
	GUI_BTN_MINUS   = (1 << 11),  // Minus (Wii/Wii U)
	GUI_BTN_HOME    = (1 << 12),  // Home (Wii/Wii U)
	GUI_TRIGGER_L   = (1 << 13),  // L Trigger / Bumper, Nunchuk C
	GUI_TRIGGER_R   = (1 << 14),  // R Trigger / Bumper
	GUI_TRIGGER_ZL  = (1 << 15),  // ZL Trigger / GC Z Button, Nunchuk Z
	GUI_TRIGGER_ZR  = (1 << 16),  // ZR Trigger
	GUI_THUMB_L     = (1 << 17),  // Left Stick Click (L3)
	GUI_THUMB_R     = (1 << 18)   // Right Stick Click (R3)
};

enum GuiHardwareProfile : uint32_t {
    GUI_HW_GAMECUBE = 0,
    GUI_HW_WIIMOTE  = 1,
    GUI_HW_NUNCHUK  = 2,
    GUI_HW_CLASSIC  = 3,
    GUI_HW_WUPC     = 4,
    GUI_HW_DRC      = 5,
    GUI_HW_MAX      = 6
};

/**
 * The universal input payload for UI elements.
 * Generated by the driver layer and consumed by GuiElement::update().
 */
struct GuiInputPadData {
	// Unified State
	uint32_t buttons_d; // Pressed this frame (down)
	uint32_t buttons_h; // Held this frame
	uint32_t buttons_r; // Released this frame
	float stickX, stickY; // Left analog stick
	float substickX, substickY; // Right analog stick (C-Stick)
	float gforceX, gforceY, gforceZ;
	float pitch, roll, yaw;
	uint32_t battery_level;
	float cursor_x, cursor_y, cursor_angle; // Wiimote / DRC
	bool validPointer;  // True if the IR pointer or touch is active on screen
	bool isTouch;       // True if input is direct touch (VPad) vs IR pointer

	bool     hw_connected[GUI_HW_MAX];
	uint32_t hw_buttons_d[GUI_HW_MAX];
	uint32_t hw_buttons_h[GUI_HW_MAX];
	uint32_t hw_buttons_r[GUI_HW_MAX];
	float    hw_stickX[GUI_HW_MAX];
	float    hw_stickY[GUI_HW_MAX];
	float    hw_substickX[GUI_HW_MAX];
	float    hw_substickY[GUI_HW_MAX];

	float    hw_gforceX[GUI_HW_MAX];
	float    hw_gforceY[GUI_HW_MAX];
	float    hw_gforceZ[GUI_HW_MAX];
	float    hw_pitch[GUI_HW_MAX];
	float    hw_roll[GUI_HW_MAX];
	float    hw_yaw[GUI_HW_MAX];

	GuiInputPadData() {
		buttons_d = buttons_h = buttons_r = 0;
		stickX = stickY = substickX = substickY = 0.0f;
		gforceX = gforceY = gforceZ = 0.0f;
		pitch = roll = yaw = 0.0f;
		battery_level = 0;
		cursor_x = cursor_y = cursor_angle = 0.0f;
		validPointer = isTouch = false;

		for(uint32_t i = 0; i < GUI_HW_MAX; i++) {
			hw_connected[i] = false;
			hw_buttons_d[i] = hw_buttons_h[i] = hw_buttons_r[i] = 0;
			hw_stickX[i] = hw_stickY[i] = hw_substickX[i] = hw_substickY[i] = 0.0f;
			hw_gforceX[i] = hw_gforceY[i] = hw_gforceZ[i] = 0.0f;
			hw_pitch[i] = hw_roll[i] = hw_yaw[i] = 0.0f;
		}
	}
};
