name: Question
description: If you have a question, please fill out this form. Feature requests will be closed immediately!
title: "[Question]: "
labels: question
body:
  - type: markdown
    attributes:
      value: Feature requests will be closed immediately!
  - type: textarea
    id: describe-question
    attributes:
      label: Describe your question
      description: Describe your question as accurately as possible.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
