name: Snes9x GX Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["Wii", "GameCube"]
    container: devkitpro/devkitppc:latest

    steps:
    - name: Install packages
      run: |
        sudo dkp-pacman-key --recv-keys C8A2759C315CFBC3429CC2E422B803BA8AA3D7CE --keyserver keyserver.ubuntu.com
        sudo dkp-pacman-key --lsign-key C8A2759C315CFBC3429CC2E422B803BA8AA3D7CE
        sudo sed -i '/^\[dkp-libs\]$/,$d' /opt/devkitpro/pacman/etc/pacman.conf
        sudo echo -e '[extremscorner-devkitpro]\nServer = https://packages.extremscorner.org/devkitpro/linux/$arch' >> /opt/devkitpro/pacman/etc/pacman.conf
        sudo dkp-pacman -Sy
        sudo dkp-pacman -S --noconfirm --ask 4 gamecube-tools-git libogc2 libogc2-libdvm
    
    - name: Checkout snes9xgx repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build Wii
      if: ${{ matrix.image == 'Wii' }}
      run: |
        make -f Makefile.wii -j2

    - name: Copy Wii artifacts
      if: ${{ matrix.image == 'Wii' }}
      run: |
        mkdir -p dist/Snes9xGX/apps/snes9xgx
        mkdir -p dist/Snes9xGX/snes9xgx/roms
        mkdir dist/Snes9xGX/snes9xgx/cheats
        mkdir dist/Snes9xGX/snes9xgx/saves
        touch dist/Snes9xGX/snes9xgx/roms/romsdir
        touch dist/Snes9xGX/snes9xgx/cheats/cheatsdir
        touch dist/Snes9xGX/snes9xgx/saves/savesdir
        cp hbc/* dist/Snes9xGX/apps/snes9xgx/
        cp executables/snes9xgx-wii.dol dist/Snes9xGX/apps/snes9xgx/boot.dol

    - name: Upload Wii artifacts
      uses: actions/upload-artifact@v4
      if: ${{ matrix.image == 'Wii' }}
      with:
        name: Snes9xGX
        path: |
          dist/Snes9xGX/

    - name: Build GameCube
      if: ${{ matrix.image == 'GameCube' }}
      run: |
        make -f Makefile.gc -j2

    - name: Copy GameCube artifact
      if: ${{ matrix.image == 'GameCube' }}
      run: |
        mkdir -p dist/Snes9xGX-GameCube
        cp executables/snes9xgx-gc.dol dist/Snes9xGX-GameCube/

    - name: Upload GameCube artifact
      uses: actions/upload-artifact@v4
      if: ${{ matrix.image == 'GameCube' }}
      with:
        name: Snes9xGX-GameCube
        path: |
          dist/Snes9xGX-GameCube/

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout snes9xgx repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist

    - name: Re-zip artifacts
      run: |
        cd dist/Snes9xGX
        rm -r snes9xgx/cheats/*
        rm -r snes9xgx/roms/*
        rm -r snes9xgx/saves/*
        zip -r ../Snes9xGX.zip *
        cd ../Snes9xGX-GameCube
        zip -r ../Snes9xGX-GameCube.zip *

    - name: Update Git Tag
      run: |
        git tag -f Pre-release
        git push -f origin Pre-release

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        prerelease: true
        allowUpdates: true
        removeArtifacts: true
        replacesArtifacts: false
        tag: Pre-release
        artifacts: "dist/*.zip"
